version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mealcrafter-postgres
    restart: always
    environment:
      POSTGRES_USER: mealcrafter
      POSTGRES_PASSWORD: mealcrafterpassword
      POSTGRES_DB: mealcrafter
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
